# Generated by Django 6.0.3 on 2026-06-04 18:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_comment_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('PD', 'Pending'), ('AP', 'Approved'), ('RJ', 'Rejected')], default='PD', max_length=2),
        ),
        migrations.AlterField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['status'], name='projects_co_status_275ea1_idx'),
        ),
    ]
