# Generated by Django 6.0.3 on 2026-06-04 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_comment_status_alter_comment_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('PD', 'در انتظار بررسی'), ('AP', 'تأیید شده'), ('RJ', 'رد شده')], default='PD', max_length=2),
        ),
    ]
